export enum EVENTS {
  FILE_OPENED = "FILE_OPENED",
  SAVE_FILE = "SAVE_FILE",
  OPEN_DIALOG = "OPEN_DIALOG",
  SHOW_FILE_IN_FOLER = "SHOW_FILE_IN_FOLER",
  EXPORT_HTML = "EXPORT_HTML",
  GET_APP_STATE = "GET_APP_STATE",
}
